name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          # git config --global user.email your_email 
          # git config --global user.name your_name 
          git config --global user.email rungruang@kkumail.com
          git config --global user.name rungruang-ops
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/rungruang-ops/portfolio.git
          git checkout -b main
          git add --all
          git commit -m "update"
          git push origin main -f